server:
  port: 8000

spring:
  application:
    name: AuthorizationServer

  cloud:
    bootstrap:
      enabled: true

    config:
      profile: dev
      discovery:
        enabled: true
        service-id: ConfigService
      enabled: true

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework:
        cloud: DEBUG

